---
- hosts: localhost
  become: true
  tasks:
  - name: Gather the package facts
    package_facts:
      manager: auto
  - name: Check for Cinnamon
    debug:
      msg: "{{ ansible_facts.packages['cinnamon'] | length }} versions of cinnamon are installed!"
    when: "'cinnamon' in ansible_facts.packages"

  - name: Install Cinnamon-Core
    apt:
      name: cinnamon-core
      state: present
  # - name: Install Cinnamon
  #   apt:
  #     name: cinnamon
  #     state: present
  #   when: "'cinnamon' in ansible_fact.packages"
      
