---
- hosts: localhost
  tasks:
  - name: Gather the package facts
    package_facts:
      manager: auto
  - name: Install Cinnamon
    apt:
      name: cinnamon
      state: present
    when: "'cinnamon' in ansible_fact.packages"
      
